# Generated by Django 2.0.2 on 2018-02-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_links_titles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
