# Generated by Django 2.0.2 on 2018-02-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180226_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='text',
            new_name='ShowcaseText',
        ),
    ]
