# Generated by Django 2.0.2 on 2018-02-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sectionbtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('cardName', models.CharField(max_length=100)),
                ('pricing', models.CharField(max_length=25)),
                ('paymentPlan', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
