# Generated by Django 2.0.2 on 2018-02-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sectiondtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(max_length=25),
        ),
    ]
