# Generated by Django 2.0.2 on 2018-02-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180227_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='MenuItem',
        ),
    ]
